### ISSUE TITLE
Difficult installation due to numpy import in setup.py

### ISSUE THREAD

**Issue by xmatthias** [roebel/py_find_1st#5]
Due to the numpy import in `setup.py`, installing this library as dependency is very difficult, since it requires to be a 2 step process at all times:

```
pip install numpy
pip install py_find_1st
```

Installing only `pip install py_find_1st` in new virtual environment results in an error.

I think this could be improved by wrapping the numpy-import into a `try/except` block, catching `ImportError`, then running a `pip install numpy` from the setup.py script and reimport numpy (this time it should not fail since numpy is now available).

I've seen this in some other project recently, but i can't currently refind that...

**Comment by roebel** [comment]
numpy is a build dependency so the proper way to handle this is by means of a pyproject.toml file that handles build dependencies with recent pip versions. I did for this issue https://github.com/roebel/pysndfile/issues/4 and it works fine. I did the same thing for py_find_1st now and you find this in version 1.1.4

I have seen here https://github.com/freqtrade/freqtrade/pull/2049 that you have problems installing in conda. Conda provides conda-build for this case, you can see the setup https://github.com/roebel/conda_packages in the py_find_1st directory. I also provide a conda package, so you could simply install like this

```
conda install -c roebel py_find_1st
```

Personally I always thought that using the system compiler with corresponding default settings would not be a good idea because your system compiler may not be compatible with the compiler settings used by conda-build in which case the binary extensions may not load.

**Comment by xmatthias** [comment]
Great! the pip problem is gone now with 1.1.4!
I didn't realize that pyproject.toml is used by pip too - I'll have to look into this in detail

conda does work too with your suggestion, thanks (although it doesn't fix my conda problem per se - since the error i get sems to result from a "problematic" conda installation ... )

**Comment by roebel** [comment]
I read on  freqtrade/freqtrade that you use windows, I would just like to clarify that the conda build packages I mentioned above don't support windows, but basically you would just need to translate the build.sh script into a corresponding build.cmd (i guess the name) script, I just fixed my py_find_1st conda_packages to use a more recent and more correct representation of the build variants  for py_find_1st 1.1.7 - good luck.

**Comment by xmatthias** [comment]
i don't primarily use windows (my problems are on linux currently - but conda is installed through pyenv - therefore i don't trust the installation 100%) but freqtrade tries to support windows too, so from time to time i test on a windows pc
